Pandas 3 and node validation fixes (#513)
Fixing two issues that fail `uv run dvc repro` currently, related to the
pandas 3 and node validation improvements.

The two errors I got were:

```
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
ERROR: failed to reproduce 'vechtstromen': failed to run: uv run python notebooks/vechtstromen/01_fix_model.py, exited with 1
```

```
LevelBoundary partition (static): missing node_ids {1757}
ERROR: failed to reproduce 'noorderzijlvest': failed to run: uv run python notebooks/noorderzijlvest/01_fix_model.py, exited with 1
```

Probably there are more, since I didn't run all stages yet. But they
tend to be relatively easy to fix, and actual improvements.