Default to overwriting in `cloud.synchronize` (#482)
We can manually turn it off for some large downloads like `top10nl` that
don't update regularly. I still need to do that for all scripts, input
welcome on which ones I should disable it for.

The reason for this is to avoid using outdated datasets unknowingly,
like in
https://github.com/Deltares/Ribasim-NL/pull/481#issuecomment-3883403058.

The real fix is tracking this input data in DVC but until we are there
we need a more robust solution.

The linked issue is not yet fixed, I run into

```
[ Info: Computation time: 1 minute, 24 seconds, 230 milliseconds
[ Info: The model finished successfully at 2026-02-13T08:35:29.120.
C:\ProgramData\DevDrives\repo\ribasim\Ribasim-NL\src\peilbeheerst_model\peilbeheerst_model\controle_output.py:207: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  self.df_basin.groupby("node_id").apply(is_stationary).reset_index(level=0, drop=True)
MAX VALUE DF_LINK 28.229695943370725
Traceback (most recent call last):
  File "C:\ProgramData\DevDrives\repo\ribasim\Ribasim-NL\notebooks\stichtse_rijnlanden\03_parameterize_model.py", line 93, in <module>
    indicators = controle_output.run_afvoer()
  File "C:\ProgramData\DevDrives\repo\ribasim\Ribasim-NL\src\peilbeheerst_model\peilbeheerst_model\controle_output.py", line 399, in run_afvoer
    control_dict = self.flow_rate(control_dict)
  File "C:\ProgramData\DevDrives\repo\ribasim\Ribasim-NL\src\peilbeheerst_model\peilbeheerst_model\controle_output.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\DevDrives\repo\ribasim\Ribasim-NL\src\peilbeheerst_model\peilbeheerst_model\controle_output.py", line 353, in flow_rate
    link_df.loc[flow_rate.index, "flow_rate"] = flow_rate
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\DevDrives\repo\ribasim\Ribasim-NL\.venv\Lib\site-packages\pandas\core\indexing.py", line 908, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "C:\ProgramData\DevDrives\repo\ribasim\Ribasim-NL\.venv\Lib\site-packages\pandas\core\indexing.py", line 775, in _get_setitem_indexer
    return self._convert_tuple(key)
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\ProgramData\DevDrives\repo\ribasim\Ribasim-NL\.venv\Lib\site-packages\pandas\core\indexing.py", line 990, in _convert_tuple
    keyidx = [self._convert_to_indexer(k, axis=i) for i, k in enumerate(key)]
              ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\ProgramData\DevDrives\repo\ribasim\Ribasim-NL\.venv\Lib\site-packages\pandas\core\indexing.py", line 1523, in _convert_to_indexer
    return self._get_listlike_indexer(key, axis)[1]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\ProgramData\DevDrives\repo\ribasim\Ribasim-NL\.venv\Lib\site-packages\pandas\core\indexing.py", line 1559, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
                      ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\ProgramData\DevDrives\repo\ribasim\Ribasim-NL\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6212, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\DevDrives\repo\ribasim\Ribasim-NL\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 6264, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: '[17, 42, 44, 749, 750, 931, 1380, 1381, 1553, 1555, 1557, 1560, 1561, 1567, 2633, 2663, 2665, 2709, 2713, 2715, 2717, 2718, 2720, 2731] not in index'
ERROR: failed to reproduce 'stichtse_rijnlanden': failed to run: uv run python notebooks/stichtse_rijnlanden/03_parameterize_model.py, exited with 1
```

Though I think that's my fault, for running with a development Ribasim
release that writes NetCDF instead of Arrow results, and it is picking
up old Arrow results, I'll check. EDIT: I made an edit in settings.py in
https://github.com/Deltares/Ribasim-NL/pull/482/changes/3fbb2bc4bb2fbfd8593f3cab41152a709d90a0e4#diff-7f820b48b1ddbf1760073470677f3276d1bc4220fb1b796947fcfedc7bf49163
such that a global RIBASIM_EXE env var won't override the .env file. In
the .env file I now set it to the 2026.1.0-rc1 release to match Ribasim
Python.

@DanielTollenaar can you explain once more how you use `check_on_remote
= False`, like `cloud.synchronize(filepaths=[ribasim_dir],
check_on_remote=False)`? You want it to download it if it is there but
it is ok if it isn't? Why can't we just remove that line?